### ISSUE TITLE
Remove the unwanted console.log .

### ISSUE THREAD

**Issue by sidjaiswal2003** [sidjaiswal2003/SocialMedia-App#3]

**Comment by Shubh8899** [comment]
I would like to work on this one.

**Comment by sidjaiswal2003** [comment]
hey shubh ! Actually  these issues are for our  college students  for the upcoming Hacktoberfest even.

**Comment by Ayush-Vish** [comment]
@sidjaiswal2003   I want to work on this issue. Can you please assign me this issue?

**Comment by sidjaiswal2003** [comment]
Go ahead

**Comment by sidjaiswal2003** [comment]
Completed
